In [13]:
graph = { 
'1' : ['2','10'], 
'2' : ['3','8'], 
'3' : ['4'], 
'4' : ['5','6','7'], 
'5' : [], 
'6' : [], 
'7' : [], 
 '8' : ['9'], 
'9' : [], 
'10' : [] 
 } 
visited = []  
queue = []  
def bfs(visited, graph, node): 
    visited.append(node) 
    queue.append(node) 
    while queue:  
        m = queue.pop(0)  
  #print (m, end = " ")  
        for neighbour in graph[m]: 
          if neighbour not in visited:  
            visited.append(neighbour) 
            queue.append(neighbour)
            print("Node visited at each time step",visited)

print("Following is the Breadth-First Search")
bfs(visited, graph, '1')  



Following is the Breadth-First Search
Node visited at each time step ['1', '2']
Node visited at each time step ['1', '2', '10']
Node visited at each time step ['1', '2', '10', '3']
Node visited at each time step ['1', '2', '10', '3', '8']
Node visited at each time step ['1', '2', '10', '3', '8', '4']
Node visited at each time step ['1', '2', '10', '3', '8', '4', '9']
Node visited at each time step ['1', '2', '10', '3', '8', '4', '9', '5']
Node visited at each time step ['1', '2', '10', '3', '8', '4', '9', '5', '6']
Node visited at each time step ['1', '2', '10', '3', '8', '4', '9', '5', '6', '7']


In [1]:
 graph = { 
 '5' : ['3','7'], 
 '3' : ['2', '4'], 
 '7' : ['6'], 
 '6': [], 
 '2' : ['1'], 
 '1':[], 
 '4' : ['8'], 
 '8' : [] 
} 
visited = set() # Set to keep track of visited nodes of graph.    
def dfs(visited, graph, node):   #function for dfs 
  if node not in visited: 
    print (node) 
    visited.add(node) 
    print("Node visited at each time step",graph[node])
    for neighbour in graph[node]: 
        dfs(visited, graph, neighbour) 
       # Driver Code 
print("Following is the Depth-First Search") 
dfs(visited, graph, '5')


Following is the Depth-First Search
5
Node visited at each time step ['3', '7']
3
Node visited at each time step ['2', '4']
2
Node visited at each time step ['1']
1
Node visited at each time step []
4
Node visited at each time step ['8']
8
Node visited at each time step []
7
Node visited at each time step ['6']
6
Node visited at each time step []


In [41]:

from collections import defaultdict 
jug1, jug2, aim = 4, 3, 2 
visited = defaultdict(lambda: False) 
def waterJugSolver(amt1, amt2): 
 if (amt1 == aim and amt2 == 0) or (amt2 == aim and amt1 == 0): 
  print(amt1, amt2) 
  return True 
 if visited[(amt1, amt2)] == False: 
  print(amt1, amt2) 
  visited[(amt1, amt2)] = True 
  return (waterJugSolver(0, amt2) or 
    waterJugSolver(amt1, 0) or 
    waterJugSolver(jug1, amt2) or 
    waterJugSolver(amt1, jug2) or 
    waterJugSolver(amt1 + min(amt2, (jug1-amt1)), 
    amt2 - min(amt2, (jug1-amt1))) or 
    waterJugSolver(amt1 - min(amt1, (jug2-amt2)), 
    amt2 + min(amt1, (jug2-amt2)))) 
 else: 
  return False 
print("Steps: ") 
waterJugSolver(0, 0)


Steps: 
0 0
4 0
4 3
0 3
3 0
3 3
4 2
0 2


True

In [40]:
def TowerOfHanoi(n , source, destination, auxiliary): 
    if n==1: 
        print ("Move disk 1 from source",source,"to destination",destination)
        return 
    TowerOfHanoi(n-1, source, auxiliary, destination) 
    print ("Move disk",n,"from source",source,"to destination",destination) 
    TowerOfHanoi(n-1, auxiliary, destination, source) 
n = 3 
TowerOfHanoi(n,'A','B','C') 



Move disk 1 from source A to destination B
Move disk 2 from source A to destination C
Move disk 1 from source B to destination C
Move disk 3 from source A to destination B
Move disk 1 from source C to destination A
Move disk 2 from source C to destination B
Move disk 1 from source A to destination B


In [39]:
from queue import PriorityQueue 
import matplotlib.pyplot as plt 
import networkx as nx 
# for implementing BFS | returns path having lowest cost def best_first_search(source, target, n): 
def best_first_search(source, target, n):
 visited = [0] * n 
 visited[source] = True 
 pq = PriorityQueue() 
 pq.put((0, source)) 
 while pq.empty() == False: 
  u = pq.get()[1] 
  print(u, end=" ") # the path having lowest cost 
  if u == target: 
     break
    
 for v, c in graph[u]: 
   if visited[v] == False: 
     pq.put((c, v)) 
print() 
# for adding edges to graph 
def addedge(x, y, cost): 
  graph[x].append((y, cost)) 
  graph[y].append((x, cost))

v = int(input("Enter the number of nodes: "))
graph = [[] for i in range(v)] # undirected Graph
e = int(input("Enter the number of edges: ")) 
print("Enter the edges along with their weights:") 
for i in range(e): 
  x, y, z = list(map(int, input().split())) 
  addedge(x, y, z) 
    
source = int(input("Enter the Source Node: ")) 
target = int(input("Enter the Target/Destination Node: "))
print("\nPath: ", end = "") 
best_first_search(source, target, v) 



Enter the number of nodes: 4
Enter the number of edges: 5
Enter the edges along with their weights:
0 1 1
0 2 1
0 3 2
2 3 2
1 3 3
Enter the Source Node: 2
Enter the Target/Destination Node: 1

Path: 2 

In [49]:

class Node():
  def __init__(self, parent=None, position=None):
    self.parent = parent
    self.position = position

    self.g = 0
    self.h = 0
    self.f = 0
  def __eq__(self, other):
    return self.position == other.position
def astar(maze, start, end):
  start_node = Node(None, start)
  start_node.g = start_node.h = start_node.f = 0
  end_node = Node(None, end)
  end_node.g = end_node.h = end_node.f = 0
  open_list = []
  closed_list = []
  open_list.append(start_node)
  while len(open_list) > 0:
    current_node = open_list[0]
    current_index = 0
    for index, item in enumerate(open_list):
      if item.f < current_node.f:
          current_node = item
          current_index = index
          open_list.pop(current_index)
          closed_list.append(current_node)
          if current_node == end_node:
             path = []
             current = current_node
             while current is not None:
               path.append(current.position)
               current = current.parent
             return path[::-1] # Return reversed path
             children = []
             for new_position in [(0, -1), (0, 1), (-1, 0), (1, 0), (-1, -1), (-1, 1), (1, -1), (1, 1)]: # Adjacent
squares
                node_position = (current_node.position[0] + new_position[0], current_node.position[1] +
new_position[1])
                 if node_position[0] > (len(maze) - 1) or node_position[0] < 0 or node_position[1] >
(len(maze[len(maze)-1]) -1) or node_position[1] < 0:
         continue
              if maze[node_position[0]][node_position[1]] != 0:
                 continue
                 new_node = Node(current_node, node_position)
                 children.append(new_node)
               for child in children:
                          for closed_child in closed_list:
                if child == closed_child:
                continue
        child.g = current_node.g + 1
        child.h = ((child.position[0] - end_node.position[0]) ** 2) + ((child.position[1] -
end_node.position[1]) ** 2)

        child.f = child.g + child.h
        for open_node in open_list:
          if child == open_node and child.g > open_node.g:
              continue
           open_list.append(child)
 def main():
  maze = [[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
  start = (0, 0)
  end = (7, 6)
  path = astar(maze, start, end)
  print(path)
if __name__ == '__main__':
main()

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 47)

In [26]:
import numpy as np
import random
from time import sleep

 def create_board():
   return(np.array([[0, 0, 0],
             [0, 0, 0],
             [0, 0, 0]]))

   def possibilities(board):
l = []

for i in range(len(board)):
  for j in range(len(board)):

     if board[i][j] == 0:
     l.append((i, j))
return(l)

def random_place(board, player):
    selection = possibilities(board)
    current_loc = random.choice(selection)
    board[current_loc] = player
    return(board)

def row_win(board, player):
   for x in range(len(board)):
       win = True

       for y in range(len(board)):
         if board[x, y] != player:
            win = False
            continue

    if win == True:
       return(win)
return(win)

def col_win(board, player):
  for x in range(len(board)):
      win = True

    for y in range(len(board)):
       if board[y][x] != player:
          win = False
          continue

    if win == True:
       return(win)
  return(win)


def diag_win(board, player):
  win = True
  y = 0
  for x in range(len(board)):
    if board[x, x] != player:
       win = False
 if win:
    return win
 win = True
 if win:
    for x in range(len(board)):
      y = len(board) - 1 - x
      if board[x, y] != player:
         win = False
  return win

def evaluate(board):
  winner = 0

for player in [1, 2]:
if (row_win(board, player) or
col_win(board,player) or
diag_win(board,player)):
winner = player
if np.all(board != 0) and winner == 0:
winner = -1


return winner
def play_game():
board, winner, counter = create_board(), 0, 1
print(board)
sleep(2)

while winner == 0:
for player in [1, 2]:
board = random_place(board, player)
print("Board after " + str(counter) + " move")
print(board)
sleep(2)
counter += 1
winner = evaluate(board)
if winner != 0:
break
return(winner)
print("Winner is: " + str(play_game()))

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 35)

In [1]:
import random


class TicTacToe:

    def __init__(self):
        self.board = []

    def create_board(self):
        for i in range(3):
            row = []
            for j in range(3):
                row.append('-')
            self.board.append(row)

    def get_random_first_player(self):
        return random.randint(0, 1)

    def fix_spot(self, row, col, player):
        self.board[row][col] = player

    def is_player_win(self, player):
        win = None

        n = len(self.board)

        # checking rows
        for i in range(n):
            win = True
            for j in range(n):
                if self.board[i][j] != player:
                    win = False
                    break
            if win:
                return win

        # checking columns
        for i in range(n):
            win = True
            for j in range(n):
                if self.board[j][i] != player:
                    win = False
                    break
            if win:
                return win

        # checking diagonals
        win = True
        for i in range(n):
            if self.board[i][i] != player:
                win = False
                break
        if win:
            return win

        win = True
        for i in range(n):
            if self.board[i][n - 1 - i] != player:
                win = False
                break
        if win:
            return win
        return False

        for row in self.board:
            for item in row:
                if item == '-':
                    return False
        return True

    def is_board_filled(self):
        for row in self.board:
            for item in row:
                if item == '-':
                    return False
        return True

    def swap_player_turn(self, player):
        return 'X' if player == 'O' else 'O'

    def show_board(self):
        for row in self.board:
            for item in row:
                print(item, end=" ")
            print()

    def start(self):
        self.create_board()

        player = 'X' if self.get_random_first_player() == 1 else 'O'
        while True:
            print(f"Player {player} turn")

            self.show_board()

            # taking user input
            row, col = list(
                map(int, input("Enter row and column numbers to fix spot: ").split()))
            print()

            # fixing the spot
            self.fix_spot(row - 1, col - 1, player)

            # checking whether current player is won or not
            if self.is_player_win(player):
                print(f"Player {player} wins the game!")
                break

            # checking whether the game is draw or not
            if self.is_board_filled():
                print("Match Draw!")
                break

            # swapping the turn
            player = self.swap_player_turn(player)

        # showing the final view of board
        print()
        self.show_board()


# starting the game
tic_tac_toe = TicTacToe()
tic_tac_toe.start()

Player X turn
- - - 
- - - 
- - - 
Enter row and column numbers to fix spot: 1 1

Player O turn
X - - 
- - - 
- - - 
Enter row and column numbers to fix spot: 2 1

Player X turn
X - - 
O - - 
- - - 
Enter row and column numbers to fix spot: 1 2

Player O turn
X X - 
O - - 
- - - 
Enter row and column numbers to fix spot: 1 3

Player X turn
X X O 
O - - 
- - - 
Enter row and column numbers to fix spot: 2 2

Player O turn
X X O 
O X - 
- - - 
Enter row and column numbers to fix spot: 3 2

Player X turn
X X O 
O X - 
- O - 
Enter row and column numbers to fix spot: 3 3

Player X wins the game!

X X O 
O X - 
- O X 


In [3]:

# Tic-Tac-Toe Program using
# random number in Python
 
# importing all necessary libraries
import numpy as np
import random
from time import sleep
 
# Creates an empty board
 
 
def create_board():
    return(np.array([[0, 0, 0],
                     [0, 0, 0],
                     [0, 0, 0]]))
 
# Check for empty places on board
 
 
def possibilities(board):
    l = []
 
    for i in range(len(board)):
        for j in range(len(board)):
 
            if board[i][j] == 0:
                l.append((i, j))
    return(l)
 
# Select a random place for the player
 
 
def random_place(board, player):
    selection = possibilities(board)
    current_loc = random.choice(selection)
    board[current_loc] = player
    return(board)
 
# Checks whether the player has three
# of their marks in a horizontal row
 
 
def row_win(board, player):
    for x in range(len(board)):
        win = True
 
        for y in range(len(board)):
            if board[x, y] != player:
                win = False
                continue
 
        if win == True:
            return(win)
    return(win)
 
# Checks whether the player has three
# of their marks in a vertical row
 
 
def col_win(board, player):
    for x in range(len(board)):
        win = True
 
        for y in range(len(board)):
            if board[y][x] != player:
                win = False
                continue
 
        if win == True:
            return(win)
    return(win)
 
# Checks whether the player has three
# of their marks in a diagonal row
 
 
def diag_win(board, player):
    win = True
    y = 0
    for x in range(len(board)):
        if board[x, x] != player:
            win = False
    if win:
        return win
    win = True
    if win:
        for x in range(len(board)):
            y = len(board) - 1 - x
            if board[x, y] != player:
                win = False
    return win
 
# Evaluates whether there is
# a winner or a tie
 
 
def evaluate(board):
    winner = 0
 
    for player in [1, 2]:
        if (row_win(board, player) or
                col_win(board, player) or
                diag_win(board, player)):
 
            winner = player
 
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner
 
# Main function to start the game
 
 
def play_game():
    board, winner, counter = create_board(), 0, 1
    print(board)
    sleep(2)
 
    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print("Board after " + str(counter) + " move")
            print(board)
            sleep(2)
            counter += 1
            winner = evaluate(board)
            if winner != 0:
                break
    return(winner)
 
 
# Driver Code
print("Winner is: " + str(play_game()))


[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [0 0 0]
 [0 0 1]]
Board after 2 move
[[0 0 0]
 [0 2 0]
 [0 0 1]]
Board after 3 move
[[0 0 0]
 [1 2 0]
 [0 0 1]]
Board after 4 move
[[0 0 2]
 [1 2 0]
 [0 0 1]]
Board after 5 move
[[0 0 2]
 [1 2 0]
 [1 0 1]]
Board after 6 move
[[0 0 2]
 [1 2 0]
 [1 2 1]]
Board after 7 move
[[0 1 2]
 [1 2 0]
 [1 2 1]]
Board after 8 move
[[2 1 2]
 [1 2 0]
 [1 2 1]]
Board after 9 move
[[2 1 2]
 [1 2 1]
 [1 2 1]]
Winner is: -1


In [19]:
 global N
 N = 4
 def printSolution(board):
  for i in range(N):
   for j in range(N):
    print (board[i][j], end = " ")
   print()

 def isSafe(board, row, col):
  for i in range(col):
   if board[row][i] == 1:
    return False

 for i, j in zip(range(row, -1, -1),
        range(col, -1, -1)):
  if board[i][j] == 1:
   return False

 for i, j in zip(range(row, N, 1),
        range(col, -1, -1)):
  if board[i][j] == 1:
   return False
  return True
 def solveNQUtil(board, col):
  if col >= N:
   return True
 for i in range(N):
  if isSafe(board, i, col):
   board[i][col] = 1
  if solveNQUtil(board, col + 1) == True:
   return True
  board[i][col] = 0
 return False
 def solveNQ():
  board = [ [0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0] ]
 if solveNQUtil(board, 0) == False:
  print ("Solution does not exist")
  return False
 printSolution(board)
 return True
solveNQ()

SyntaxError: 'return' outside function (Temp/ipykernel_15400/273391612.py, line 17)

In [20]:
global N
N = 4
def printSolution(board):
    for i in range(N):
        for j in range(N):
            print (board[i][j], end = " ")
        print()
        
def isSafe(board, row, col):
    for i in range(col):
        if board[row][i] == 1:
            return False
    for i, j in zip(range(row, -1, -1),
        range(col, -1, -1)):
        if board[i][j] == 1:
            return False
    for i, j in zip(range(row, N, 1),
        range(col, -1, -1)):
        if board[i][j] == 1:
            return False
    return True

def solveNQUtil(board, col):
    if col >= N:
        return True
    for i in range(N):
        if isSafe(board, i, col):
            board[i][col] = 1 
            if solveNQUtil(board, col + 1) == True:
                return True
            board[i][col] = 0
    return False
    
def solveNQ():
    board = [ [0, 0, 0, 0],
              [0, 0, 0, 0],
              [0, 0, 0, 0],
              [0, 0, 0, 0] ]
    if solveNQUtil(board, 0) == False:
        print ("Solution does not exist")
        return False
    printSolution(board)
    return True

solveNQ()

0 0 1 0 
1 0 0 0 
0 0 0 1 
0 1 0 0 


True